apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: InfluxDB
    orgId: 1


datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    version: 1
    editable: true

  - name: Loki
    type: loki
    uid: loki
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true

  - name: InfluxDB
    type: influxdb
    uid:  influxdb
    orgId: 1
    url: http://influxdb:8086
    basicAuth: false
    database: geth
    user: admin
    password: admin
    version: 1
    editable: true
